name: Test Input Passing and Repository Installation

on:
  workflow_dispatch:
    inputs:
      issue_number:
        required: true
        type: number
      llm_models:
        required: true
        type: string
      llm_api_key:
        required: true
        type: string
      firebase_config:
        required: true
        type: string
      base_url:
        required: true
        type: string
      pat_token:
        required: true
        type: string
      pat_username:
        required: true
        type: string

permissions:
  contents: read

jobs:
  test-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Print all inputs (For Debugging)
        run: |
          echo "Issue Number: ${{ inputs.issue_number }}"
          echo "LLM Models: ${{ inputs.llm_models }}"
          echo "LLM API Key: ${{ inputs.llm_api_key }}"
          echo "Firebase Config: ${{ inputs.firebase_config }}"
          echo "Base URL: ${{ inputs.base_url }}"
          echo "PAT Token: ${{ inputs.pat_token }}"
          echo "PAT Username: ${{ inputs.pat_username }}"

      - name: Check required environment variables
        env:
          LLM_MODELS: ${{ inputs.llm_models }}
          LLM_API_KEY: ${{ inputs.llm_api_key }}
          LLM_BASE_URL: ${{ inputs.base_url }}
          PAT_TOKEN: ${{ inputs.pat_token }}
          PAT_USERNAME: ${{ inputs.pat_username }}
        run: |
          required_vars=("LLM_MODELS" "LLM_API_KEY" "PAT_TOKEN" "PAT_USERNAME" "LLM_BASE_URL")
          for var in "${required_vars[@]}"; do
            if [ -z "${!var}" ]; then
              echo "Error: Required environment variable $var is not set."
              exit 1
            fi
          done

      - name: Set issue number
        run: echo "ISSUE_NUMBER=${{ inputs.issue_number }}" >> $GITHUB_ENV

      - name: Comment on issue with start message
        uses: actions/github-script@v7
        with:
          github-token: ${{ inputs.pat_token }}
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ env.ISSUE_NUMBER }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Test Workflow is triggered! You can monitor the progress [here](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}).`
            });

      # - name: Install Repository (Test pip Install)
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install git+https://github.com/JiseungHong/test.git

      # - name: Execute Test Python File
      #   env:
      #     GITHUB_TOKEN: ${{ inputs.pat_token }}
      #     LLM_MODELS: ${{ inputs.llm_models }}
      #     LLM_API_KEY: ${{ inputs.llm_api_key }}
      #     LLM_BASE_URL: ${{ inputs.base_url }}
      #     GITHUB_USERNAME: ${{ inputs.pat_username }}
      #     PYTHONPATH: ""
      #     FIREBASE_CONFIG: ${{ inputs.firebase_config }}
      #   run: |
      #     cd /tmp && python -m test-python

      - name: Confirm Successful Execution
        run: echo "✅ Successfully verified input passing and repository installation."
